### ISSUE TITLE
`DeserializeError` not visible

### ISSUE THREAD

**Issue by jsimpson-gro** [gwierzchowski/csv-async#16]
It looks like the `DeserializeError` and `DeserializeErrorKind` aren't visible outside the crate.

https://docs.rs/csv-async/1.2.5/csv_async/enum.ErrorKind.html

**Comment by gwierzchowski** [comment]
Thanks for reporting.
I will look around and fix possibly in next 1-3 weeks.
Most probably will introduce new methods: `Error::sub_kind()` and `Error::field()` which will provide access to some underlying error details (like `DeserializeErrorKind` or `Utf8Error`).

In longer perspective I'll probably make breaking change and rewrite it into `thiserror`.

**Comment by jsimpson-gro** [comment]
Much appreciated. I was short on time in the original issue and left out context. I'm extracting error detail to craft an application specific error message so my users can troubleshoot w/o me.

**Comment by gwierzchowski** [comment]
@jsimpson-gro - Eventually did not created `Error::sub_kind()` because `pos` and `err` even if private can be de-structured but made Deserialize error structures public as you suggested. - please check if above MR works for you.
