### ISSUE TITLE
Doc-hidden enum variants can be replaced by non_exhaustive attribute

### ISSUE THREAD

**Issue by A248** [gwierzchowski/csv-async#23]
The [`#[non_exhaustive]`](https://doc.rust-lang.org/reference/attributes/type_system.html) attribute is intended to prevent exhaustive matching on enums. A benefit of the attribute is that code within the same crate (i.e., within csv-async) can perform exhaustive matching, although client code in other crates cannot.

For example, `QuoteStyle::__Nonexhaustive` would be obsoleted by adding `#[non_exhaustive]` on the enum.
```rust
#[non_exhaustive]
pub enum QuoteStyle {
    Always,
    Necessary,
    NonNumeric,
    Never
}
```

A further benefit is that exhaustive matching will no longer compile in client code, and this restriction is enforced by the compiler. Technically speaking, the following code currently compiles. Such code would technically be "broken" by using the `#[non_exhaustive]` attribute; however, I think the documentation is clear that `QuoteStyle::__Nonexhaustive` and friends are not to be used seriously.

```rust
// This currently compiles, but will no longer compile if we use #[non_exhaustive]
let qs = csv_async::QuoteStyle::__Nonexhaustive;
match qs {
    QuoteStyle::Always => {}
    QuoteStyle::Necessary => {}
    QuoteStyle::NonNumeric => {}
    QuoteStyle::Never => {}
    QuoteStyle::__Nonexhaustive => {}
};
```

If you'd like me to, let me know and I'll make a PR.

**Comment by gwierzchowski** [comment]
Thanks for heads up. I like this idea. PR welcome.
PS: There are few other places in crate affected by this - correct in all of them.
