### ISSUE TITLE
Flush on every call to `serialize`

### ISSUE THREAD

**Issue by andyquinterom** [gwierzchowski/csv-async#25]
I am writing a microservice that constantly streams CSV output. I see that documentation calls for NOT using a buffered writer, however, I see it is still pretty much necesary.

Taking a look at the source code I see that `serialize` calls flush.

```rust
    pub async fn serialize<S: Serialize>(&mut self, record: S) -> Result<()> {
        self.ser_wtr.serialize(record)?;
        self.ser_wtr.flush()?;
        self.asy_wtr.as_mut().unwrap().write_all(self.ser_wtr.data()).await?;
        self.ser_wtr.clear();
        Ok(())
    }
```

**Comment by gwierzchowski** [comment]
This `flush` call is actually in-memory only, between internal buffer and `MemWriter` writer which is a vector. It does not involve any i/o.
