### ISSUE TITLE
Tokio 1.0 release

### ISSUE THREAD

**Issue by giacomocariello** [gwierzchowski/csv-async#4]
Hi, I noticed your latest commit enables tokio 1.0 AsyncRead's. I was wondering if you could post a new release on crates.io.

**Comment by gwierzchowski** [comment]
Hi, I would like to analyze and possibly merge pending PR first, and have one more simple change to do before I publish.
Roughly estimate, that will be publishing in about 2 weeks.

**Comment by gwierzchowski** [comment]
Just published new version 1.2.0 with Tokio 1 compatibility and few other changes on crates.io
